basePath: /api/v1
definitions:
  private.LogDTO:
    properties:
      content:
        type: string
      id:
        type: string
      labRoadID:
        type: integer
      languageID:
        type: integer
      type:
        type: string
      userId:
        type: string
    type: object
  private.StartDTO:
    properties:
      languageID:
        type: integer
    required:
    - languageID
    type: object
  public.LoginDTO:
    properties:
      password:
        description: Password is required and must be at least 8 characters
        minLength: 8
        type: string
      username:
        description: Username is required, must be alphanumeric and between 3-30 characters
        maxLength: 30
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  public.RegisterDTO:
    properties:
      githubProfile:
        description: Github Profile is must be max 30 characters long.
        maxLength: 30
        type: string
      name:
        description: Name is required
        type: string
      password:
        description: Password is required and must be at least 8 characters
        minLength: 8
        type: string
      surname:
        description: Surname is required
        type: string
      username:
        description: Username is required, must be alphanumeric and between 3-30 characters
        maxLength: 30
        minLength: 3
        type: string
    required:
    - name
    - password
    - surname
    - username
    type: object
  response.BaseResponse:
    properties:
      data: {}
      data_count:
        type: integer
      errors: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Service for CodinLab
  title: API Service
  version: v1
paths:
  /private/log:
    get:
      consumes:
      - application/json
      description: Retrieves all logs based on the provided query parameters.
      parameters:
      - description: User ID
        in: query
        name: userID
        type: string
      - description: Language ID
        in: query
        name: languageID
        type: integer
      - description: Log Lab or Road ID
        in: query
        name: labRoadID
        type: integer
      - description: Log Content
        in: query
        name: content
        type: string
      - description: Log Type
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.BaseResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/private.LogDTO'
                  type: array
              type: object
      summary: Get all logs
      tags:
      - Log
  /private/road/start:
    post:
      consumes:
      - application/json
      description: Start
      parameters:
      - description: Start
        in: body
        name: start
        required: true
        schema:
          $ref: '#/definitions/private.StartDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Start
      tags:
      - Road
  /public/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/public.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Login
      tags:
      - Auth
  /public/register:
    post:
      consumes:
      - application/json
      description: Register
      parameters:
      - description: Register
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/public.RegisterDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Register
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: cookie
    name: session_id
    type: apiKey
swagger: "2.0"
